### PR TITLE
Ticket 13 spaceship packet unit test implementation

### PR DESCRIPTION
**Pull request by stank3391**
I have implemented Ticket 13:

- Spaceship class: Constructor, Add data method, and timer. Other methods left as stubs. Implementation is currently blocked.
- Packetwrapper class: Constructor, toJson, crc keft as stub for later implementation
- SpaceshipReadings interface: I have written the interface and created a stub to use as object dummies
- Unit tests for tojson

### CODE REVIEW

**Review by ywang0789 — APPROVED** [review]
👍

**Comment by jschulz8138** [comment]
Small nitpicks such as removing unused using System; in SpaceShip.cs, but looks good to me

**Review by jschulz8138 — COMMENTED** [review]
👍

**Comment by stank3391** [comment]
> Small nitpicks such as removing unused using System; in SpaceShip.cs, but looks good to me

Thanks Justin, I will remove these in a future commit! \o/

**Pull request merged**
